cs/src/Contracts/ResourceStatus.cs
cs/src/Contracts/TunnelContracts.cs
cs/src/Management/TunnelManagementClient.cs
cs/tools/TunnelsSDK.Generator/JavaContractWriter.cs
cs/tools/TunnelsSDK.Generator/TSContractWriter.cs
go/tunnels/manager_test.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelAccessControlEntryType.java
java/src/main/java/com/microsoft/tunnels/contracts/TunnelConnectionMode.java
java/src/main/java/com/microsoft/tunnels/contracts/TunnelContracts.java
java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java
java/src/test/java/com/microsoft/tunnels/TunnelContractsTests.java
ts/src/contracts/tunnelPortStatus.ts
ts/src/contracts/tunnelStatus.ts

Instead of renaming the `hostConnectionCount` and `clientConnectionCount` status properties, this change makes `ResourceStatus` serialization backward-compatible by supporting both the simple number and object (current + limit) format, using custom serializers for C#, Go, and Java, and a union type for TS.
Also, Java JSON serialization config code is refactored into a `TunnelContracts` static class, to match how it was done in C#.

Fix ResourceStatus serialization

---

cs/tools/TunnelsSDK.Generator/GoContractWriter.cs
cs/tools/TunnelsSDK.Generator/TSContractWriter.cs
go/tunnels/tunnel_access_control_entry_type.go
go/tunnels/tunnel_connection_mode.go
ts/src/contracts/tunnelAccessControlEntryType.ts
ts/src/contracts/tunnelConnectionMode.ts

Fixes: https://github.com/microsoft/basis-planning/issues/351
C# and (generated) Java code use PascalCase for enum values, while the generated TS & Go code used camelCase. This inconsistency could cause problems when directly comparing enum values in TS & Go with values returned by the service (which are PascalCase).

Fix casing for generated TS & Go enum values

---

cs/src/Management/TunnelManagementClient.cs
cs/src/Management/UnauthorizedAccessExceptionExtensions.cs

Fix the C# tunnel management client to propagate additional parameters related to custom auth in case of an unauthorized error. (Other language SDKs don't currently have any special handling of the WWW-Authenticate response header.)

Include auth params in unauthorized exception

---

cs/src/Management/TunnelManagementClient.cs
cs/src/Management/UnauthorizedAccessExceptionExtensions.cs

The tunnel service can potentially return multiple values for the `WWW-Authenticate` header. The multiple values were not getting propagated as expected by the SDK client due to a bug or limitation in .NET's `HttpResponseHeaders` class.

Fix handling of multiple WWW-Authenticate header values

---

cs/src/Management/TunnelManagementClient.cs

This fixes a bug in my [previous PR](https://github.com/microsoft/dev-tunnels/pull/89): it threw an exception when the service returned 403 without any `WWW-Authenticate` header.

Fix WWW-Authenticate header bug

---

cs/src/Management/TunnelRequestOptions.cs

Change `TunnelRequestOptions.ToQueryString()` from `internal` to `protected internal virtual`, so it can be possible to make a subclass that adds new query parameters.

Make TunnelRequestOptions extensible

---

cs/src/Contracts/TunnelPort.cs
go/tunnels/tunnel_port.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelPort.java
rs/src/contracts/tunnel_access_control_entry.rs
rs/src/contracts/tunnel_access_control_entry_type.rs
rs/src/contracts/tunnel_port.rs
ts/src/contracts/tunnelPort.ts

This change adds `name`, `description`, and `tags` properties to the `TunnelPort` contract. These properties will give applications more options for working with multiple ports of a tunnel. They're currently ignored by the tunnel service, but will be implemented later.

Add name, description, & tags props to TunnelPort

---

cs/src/Management/ITunnelManagementClient.cs
cs/src/Management/TunnelManagementClient.cs
cs/src/Management/TunnelRequestOptions.cs
go/tunnels/manager.go
go/tunnels/request_options.go
java/src/main/java/com/microsoft/tunnels/management/ITunnelManagementClient.java
java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java
java/src/main/java/com/microsoft/tunnels/management/TunnelRequestOptions.java
rs/src/management/http_client.rs
rs/src/management/tunnel_request_options.rs
ts/src/management/tunnelManagementClient.ts
ts/src/management/tunnelManagementHttpClient.ts
ts/src/management/tunnelRequestOptions.ts
ts/test/tunnels-test/mocks/mockTunnelManagementClient.ts
ts/test/tunnels-test/tunnelManagementTests.ts

The "search" API was originally designed to search tunnels by tags across all users, returning any matching tunnels that the caller had some access to. But that kind of search is too expensive, and not useful in any known scenarios. This update replaces that function with a more limited option to include tags as a filter to the "list" API that only covers tunnels owned by the caller. And since ports will also soon support tags, and tags are just one of many query options, I'm moving the tags option to the general request options class.
- Mark the `SearchTunnelsAsync()` API as `[Obsolete]` in C#; remove it in the other 4 languages. We'll remove it from C# in the future.
- Add `Tags` and `RequireAllTags` to `TunnelRequestOptions`, and update `ToQueryString()` to include those parameters …

Move search tags to request options

---

java/pom.xml

The version number in the published POM was not correctly being rewritten to the `revision` variable passed in through our GH publish action. This was causing problems installing the latest version using gradle (maven works fine). The flatten plugin takes care of this. See https://maven.apache.org/maven-ci-friendly.html#install-deploy.
Compare the version property in the POM of [1.4](https://github.com/microsoft/dev-tunnels/packages/1375564?version=0.1.4) published from this branch with the POM of [1.3](https://github.com/microsoft/dev-tunnels/packages/1375564?version=0.1.3) from main.

Add flatten plugin to correctly resolve revision variable in mvn deploy

---

rs/Cargo.lock
rs/Cargo.toml

The `ruestc-serialize` dependency is not used and triggered a dependabot alert: https://github.com/microsoft/dev-tunnels/security/dependabot/6

Remove unused reference to rustc-serialize

---

cs/src/Management/TunnelAccessTokenProperties.cs
cs/src/Management/TunnelManagementClient.cs
java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java
ts/src/connections/tunnelRelayTunnelClient.ts
ts/src/connections/tunnelRelayTunnelHost.ts
ts/src/management/index.ts
ts/src/management/tunnelAccessTokenProperties.ts
ts/src/management/tunnelManagementHttpClient.ts

Fixes: https://github.com/microsoft/basis-planning/issues/88
Fixes: https://github.com/microsoft/basis-planning/issues/224#issuecomment-1197070218
- Add new `TunnelAccessTokenProperties` class that is capable of parsing tunnel access token JWTs. (Only in C# and TS for now.)
- Check access token expiration date in the client before attempting to use the token in a request.
- Note this does not apply to AAD/GH user tokens because those are opaque to us: AAD tokens are encrypted and GH tokens are not JWTs.
- When tracing TS client requests, replace access token with the token properties. The token properties are helpful for diagnostics but don't need to be kept secret like the actual token. Also redact AAD & GH tokens in the Authorization header.
- C# client tracing is done via an HTTP …

Redact tokens from log, check expiration on client

---

cs/src/Connections/ConnectionStatus.cs
cs/src/Connections/ConnectionStatusChangedEventArgs.cs
cs/src/Connections/IRelayClient.cs
cs/src/Connections/ITunnelClient.cs
cs/src/Connections/ITunnelConnector.cs
cs/src/Connections/ITunnelHost.cs
cs/src/Connections/MultiModeTunnelClient.cs
cs/src/Connections/MultiModeTunnelHost.cs
cs/src/Connections/RefreshingTunnelAccessTokenEventArgs.cs
cs/src/Connections/RelayTunnelConnector.cs
cs/src/Connections/TunnelBase.cs
cs/src/Connections/TunnelClientBase.cs
cs/src/Connections/TunnelHostBase.cs
cs/src/Connections/TunnelRelayTunnelClient.cs
cs/src/Connections/TunnelRelayTunnelHost.cs
cs/src/Connections/WebSocketStream.cs
cs/src/Management/TunnelAccessTokenProperties.cs
cs/test/TunnelsSDK.Test/LocalPortsFixture.cs
cs/test/TunnelsSDK.Test/Mocks/MockTunnelRelayStreamFactory.cs
cs/test/TunnelsSDK.Test/TestTunnelRelayTunnelClient.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs
cs/test/TunnelsSDK.Test/TunnelsSDK.Test.csproj

Fix for [#412](https://github.com/microsoft/basis-planning/issues/412) and [#413](https://github.com/microsoft/basis-planning/issues/413)
- Enable SSH session reconnection.
- Retry connection to Relay server when it fails, or is disconnected with exponential backoffs.
- Do not retry on unrecoverable errors.
- Handle 401 errors and fire a new event to let the customers supply a fresh tunnel access token.
- Abstract relay connection logic into a separate class and use it from the tunnel client and host
- Add a common base class for the tunnel client and host, and add an event for tunnel access token refresh there.
- Add some unit tests; more incoming later.

Make SDK cs client reconnect SSH host and client sessions

---

cs/src/Connections/TunnelHostBase.cs
cs/src/Connections/TunnelRelayTunnelHost.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs

There is a small time interval in `ForwardPortAsync()` between the port being forwarded with `ForwardFromRemotePortAsync()` and `RemoteForwarders` updated.
See https://github.com/microsoft/basis-planning/issues/467
The check is redundant because setting `AcceptRemoteConnectionsForNonForwardedPorts` to false makes PFS reject forwarding requests from the clients for the ports that are not forwarded and are missing in `PFS.remoteConnectors`.
Call to `PFS.ForwardFromRemotePortAsync()` in `ForwardPortAsync()` adds the connector to `PFS.remoteConnectors`.

Do not check host RemoteForwarders when PFS channel opens

---

rs/Cargo.toml
rs/src/management/authorization.rs
rs/src/management/errors.rs
rs/src/management/http_client.rs

Using a trait here works _much_ better than trying to take a free-floating function. Making the trait as `Send + Sync` requires it to be usable and sendable on multiple threads, which avoids the previous issues we faced.
Consumers can implement the trait like so,
```rs
#[async_trait]
impl AuthorizationProvider for Auth {
async fn get_authorization(&self) -> Result<Authorization, HttpError> {
self.get_basis_authentication()
.await
.map_err(|e| HttpError::AuthorizationError(e.to_string()))
}
}
```

rs: re-add support for async auth providers

---

cs/src/Management/TunnelManagementClient.cs
ts/src/management/tunnelManagementHttpClient.ts

- Define protected `SendTunnelRequestAsync()` and `SendRequestAsync()` methods in C# `TunnelManagementClient` enabling subclasses to support additional management APIs without duplicating a lot of code to format requests and handle responses and errors. (We'll use this for internal APIs.)
- Apply equivalent changes to TS. (No specific need for this yet but it's good to keep parity with C#.)
- Fix handling of 404 responses in TS which was not correct for some APIs.
I tried to make the new APIs cleaner and more consistent, and they are well-documented. The PR diff has a lot of changes but much of it is just renaming/reordering parameters, or doc-comments.

Make TunnelManagementClient extensible

---

cs/src/Connections/IRelayClient.cs
cs/src/Connections/MultiModeTunnelClient.cs
cs/src/Connections/MultiModeTunnelHost.cs
cs/src/Connections/RelayTunnelConnector.cs
cs/src/Connections/RetryingTunnelConnectionEventArgs.cs
cs/src/Connections/TunnelBase.cs
cs/src/Connections/TunnelClient.cs
cs/src/Connections/TunnelConnection.cs
cs/src/Connections/TunnelConnectionException.cs
cs/src/Connections/TunnelHost.cs
cs/src/Connections/TunnelRelayTunnelClient.cs
cs/src/Connections/TunnelRelayTunnelHost.cs
cs/src/Connections/WebSocketStream.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs

- Add `RetryingTunnelConnection` event on the base connection class, and update `RelayTunnelConnector` to invoke the event when processing retries.
- Rename `TunnelBase` -> `TunnelConnection` because it has the connection behavior that is shared between host and client subclasses. (It's not the base of a Tunnel.) Also rename `TunnelHostBase`->`TunnelHost` and `TunnelClientBase`->`TunnelClient` because the "Base" suffix is not conventionally used in public APIs.
- Refactor get/set of HTTP status code for an exception, and expose that as a property on `TunnelConnectionException`.

Add event to enable observing & cancelling tunnel connection retries

---

cs/src/Connections/ITunnelClient.cs
cs/src/Connections/ITunnelHost.cs
cs/src/Connections/MultiModeTunnelClient.cs
cs/src/Connections/MultiModeTunnelHost.cs
cs/src/Connections/TunnelClient.cs
cs/src/Connections/TunnelHost.cs
cs/src/Connections/TunnelRelayTunnelHost.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs
ts/.npmrc
ts/src/connections/multiModeTunnelClient.ts
ts/src/connections/multiModeTunnelHost.ts
ts/src/connections/tunnelClient.ts
ts/src/connections/tunnelClientBase.ts
ts/src/connections/tunnelHost.ts
ts/src/connections/tunnelHostBase.ts
ts/src/connections/tunnelRelayTunnelHost.ts
ts/test/tunnels-test/connectTests.ts
ts/test/tunnels-test/tunnelHostAndClientTests.ts

Fixes: https://github.com/microsoft/basis-planning/issues/450
These changes enable a client with management access to update the set of forwarded ports on an actively hosted tunnel.
- Add `RefreshPortsAsync()` API to `ITunnelHost` and `ITunnelClient`
- Implement on the host side by using the management client to get the updated list of ports, and updating SSH port-forwarding state accordingly.
- Implement on the client side by sending a special SSH request message of type `RefreshPorts` to the host, that simply triggers the above operation.
- Remove Add/Update/Remove ports APIs from `ITunnelHost`. Any calls to those should be replaced by calls to the equivalent management APIs, followed by `RefreshPortsAsync()`. Test code is updated accordingly.
**TODO**: (soon) Port changes to other SDK …

API to make host refresh ports from service

---

cs/src/Contracts/TunnelAccessControl.cs
cs/src/Contracts/TunnelAccessScopes.cs
cs/src/Management/TunnelManagementClient.cs
cs/src/Management/TunnelRequestOptions.cs
go/tunnels/access_scopes.go
go/tunnels/manager.go
go/tunnels/manager_test.go
go/tunnels/request_options.go
go/tunnels/tunnel_access_scopes.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelAccessControl.java
java/src/main/java/com/microsoft/tunnels/contracts/TunnelAccessControlStatics.java
java/src/main/java/com/microsoft/tunnels/contracts/TunnelAccessScopes.java
java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java
java/src/main/java/com/microsoft/tunnels/management/TunnelRequestOptions.java
java/src/test/java/com/microsoft/tunnels/TunnelContractsTests.java
rs/Cargo.lock
rs/src/contracts/tunnel_access_scopes.rs
rs/src/management/http_client.rs
rs/src/management/tunnel_request_options.rs
ts/src/contracts/tunnelAccessControlStatics.ts
ts/src/contracts/tunnelAccessScopes.ts
ts/src/management/tunnelManagementHttpClient.ts
ts/src/management/tunnelRequestOptions.ts
ts/test/tunnels-test/tunnelManagementTests.ts

Add SDK support for a new `manage:ports` scope, and for requesting access tokens with a space-delimited combination of scopes, such as `connect manage:ports`.
Note attempts to use the new scope will be rejected by the tunnel service as invalid until the server-side support lands. I'm working on that separately.
Related: https://github.com/microsoft/basis-planning/issues/450

 Add manage:ports access scope

---

.github/workflows/maven.yml
java/README.md
java/src/test/java/com/microsoft/tunnels/TunnelClientTests.java
java/src/test/java/com/microsoft/tunnels/TunnelManagementClientTests.java
java/src/test/java/com/microsoft/tunnels/TunnelTest.java

* Reenables Java `TunnelMangementClient` tests locally using an env variable to supply the auth token.
* Adds a `TunnelClient` connection test and readme to set up with a CLI hosted tunnel.

Enable Java tests for local development

---

go/tunnels/tunnels.go

This skips from 0.0.4 to 0.0.6 since 0.0.5 is already published

Update Go Package Version

---

cs/src/Contracts/TunnelEndpoint.cs
go/tunnels/tunnel_endpoint.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelEndpoint.java
rs/src/contracts/tunnel_endpoint.rs
ts/src/contracts/tunnelEndpoint.ts

Add ssh gateway public key to tunnel endpoint which will be used in CLI to show it user to add the public key to authorized_keys file.

Add ssh gateway public key to tunnel endpoint

---

rs/Cargo.lock
rs/Cargo.toml
rs/src/connections/errors.rs
rs/src/connections/host_relay.rs
rs/src/connections/io.rs
rs/src/connections/mod.rs
rs/src/connections/relay_tunnel_host.rs
rs/src/connections/ws.rs
rs/src/lib.rs
rs/src/management/http_client.rs
rs/src/management/tunnel_locator.rs

This implement a host relay. It does not yet implement reconnections,
although with that added in consumer code this has been working fairly
well for me, and I've been using this for my day-to-date work.
The relay is opt-in under the `connections` feature flag.
This PR is marked as draft until russh publishes their next version,
at which time I'll update the Cargo.toml and this'll be ready to go.

rs: implement initial host relay 

---

cs/src/Connections/TunnelRelayTunnelHost.cs
cs/src/Management/TunnelRequestOptions.cs
go/tunnels/request_options.go
java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java
java/src/main/java/com/microsoft/tunnels/management/TunnelRequestOptions.java
ts/src/connections/tunnelRelayTunnelHost.ts
ts/src/management/tunnelManagementHttpClient.ts
ts/src/management/tunnelRequestOptions.ts

Add AdditionalQueryParameters for users of SDK to send additional query parameters.
Send additional parameter to include ssh gateway public key when calling UpdateTunnelEndpoint api if there is atleast one ssh port.

Add AdditionalQueryParameters and include ssh gateway public key in UpdateTunnelEndpoint

---

rs/src/management/http_client.rs
rs/src/management/tunnel_locator.rs

We use this in VS Code to derive a client that uses host tokens from the "base" client that users user auth.

rs: allow rebuilding the client with new options

---

cs/src/Contracts/RateStatus.cs
go/tunnels/resource_status.go
java/src/main/java/com/microsoft/tunnels/contracts/RateStatus.java
rs/src/contracts/rate_status.rs
ts/src/contracts/rateStatus.ts

This changes the resetSeconds field to resetTime. This should allow for more efficient tracking of when the current value should be reset to 0 as we can just check this value against the current time. This should not change anything as the ResetSeconds field appears to not be used anywhere in the service outside the mapper. This will allow the relay pods to reset status on their own

Update rate status contract reset time

---

ts/src/connections/tunnelRelayTunnelHost.ts
ts/test/tunnels-test/tunnelHostAndClientTests.ts

The service E2E tests are currently running on an older version of the TS SDK (`1.0.7280`, and latest is `1.0.7298`), and updating the package fails the tests. Changes in the newer packages are causing us to check the hosts `remoteForwarders` for a local port instead of a remote port on `forwarded-tcpip` requests here:
https://github.com/microsoft/dev-tunnels/blob/c02ac44d6262a2775420904a5690d60ae8cfc6b9/ts/src/connections/tunnelHostBase.ts#L120
Updating the TypeScript SDK with the corresponding C# change from this PR fixes the E2E tests:
https://github.com/microsoft/dev-tunnels/pull/116
Also added a TS version of one of the tests from the other PR, though I don't think it actually tests the behavior in question.

(TS) don't check remote forwarders on forwarded-tcpip request

---

cs/src/Management/TunnelManagementClient.cs
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java
ts/src/management/tunnelManagementHttpClient.ts

Port description and tags were not getting updated due to some missing assignments in the management client.

Fix port tags and description updates

---

cs/src/Management/TunnelManagementClient.cs
cs/src/Management/TunnelRequestOptions.cs
cs/test/TunnelsSDK.Test/TunnelManagementClientTests.cs

The use case is to pass custom options to a DelegatingHttpHandler that TunnelManagementClient may be using.

Add TunnelRequestOptions.HttpRequestOptions for C# SDK

---

cs/src/Contracts/TunnelHeaderNames.cs
go/tunnels/tunnel_header_names.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelHeaderNames.java
rs/src/contracts/tunnel_header_names.rs
ts/src/contracts/tunnelHeaderNames.ts

Since the service change will not use this header it should be removed

Remove antiphishing header

---

cs/src/Contracts/TunnelOptions.cs
go/tunnels/tunnel_options.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelOptions.java
rs/src/contracts/tunnel_options.rs
ts/src/contracts/tunnelOptions.ts

To let tunnels change the `Host` request header in web-forwarding, we need to pass this header to the service.

Add HostHeader tunnel option

---

.pipelines/cs-ci-build.yaml
.pipelines/typescript-build-and-publish.yaml

Enable CodeQL in CI builds
See https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/configuring-codeql3000-ado-pipelines#enabling-codeql-3000 for details.

Enable CodeQL in CI build

---

cs/src/Contracts/RateStatus.cs
cs/src/Contracts/ResourceStatus.cs
cs/src/Contracts/TunnelStatus.cs
go/tunnels/tunnel_status.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelStatus.java
rs/src/contracts/tunnel_status.rs
ts/src/contracts/tunnelStatus.ts

- Extend `TunnelStatus` properties to track `UploadRate`, `UploadTotal`, `DownloadRate`, `DownloadTotal`.
- Add `ToString()` methods in C# `ResourceStatus` and `RateStatus` classes.

Report more bandwidth details in tunnel status

---

cs/src/Management/TunnelRequestOptions.cs
go/tunnels/request_options.go
java/src/main/java/com/microsoft/tunnels/management/TunnelRequestOptions.java
rs/src/management/http_client.rs
rs/src/management/tunnel_request_options.rs
ts/src/management/tunnelManagementHttpClient.ts
ts/src/management/tunnelRequestOptions.ts

This adds a param to the tunnel list command to limit the number of tunnels returned. This can speed up queries to control plane when searching for single tunnels by tags

Add Limit Param to List Operation

---

cs/src/Contracts/TunnelAccessSubject.cs
cs/src/Contracts/TunnelConstraints.cs
cs/tools/TunnelsSDK.Generator/GoContractWriter.cs
cs/tools/TunnelsSDK.Generator/JavaContractWriter.cs
cs/tools/TunnelsSDK.Generator/RustContractWriter.cs
cs/tools/TunnelsSDK.Generator/TSContractWriter.cs
go/tunnels/tunnel_constraints.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelConstraints.java
rs/src/contracts/tunnel_constraints.rs
ts/src/contracts/tunnelConstraints.ts

- Add `:` and `/` characters to subject regex, to support IP addresses and ranges.
- Make subject name constraints public.
- Fix quote escaping in code generation.

Fix subject regex, expose more constraints

---

java/README.md
java/src/main/java/com/microsoft/tunnels/connections/TcpipForwardRequestHandler.java
java/src/test/java/com/microsoft/tunnels/TunnelClientTests.java
java/src/test/java/com/microsoft/tunnels/TunnelTest.java

* Respond to `tcpip-forward` request with success if the requested port is already in the forwarded ports collection. 
* Add test for adding and removing ports.

Add Java refresh ports tests

---

cs/src/Contracts/Tunnel.cs
go/tunnels/tunnel.go
java/src/main/java/com/microsoft/tunnels/contracts/Tunnel.java
rs/src/contracts/tunnel.rs
ts/src/contracts/tunnel.ts

This property will be returned from tunnel get operations and will contain the value of when the tunnel with be cleaned up if it is not used or updated.

Add tunnel expiration property to contracts

---

cs/src/Contracts/TunnelConstraints.cs
go/tunnels/tunnel_constraints.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelConstraints.java
rs/src/contracts/tunnel_constraints.rs
ts/src/contracts/tunnelConstraints.ts

Fixes E2E test failures, with test cases that use MSA emails as the subject ID and org/team format as a subject name.

Add valid chars to subject name and email regexes

---

cs/src/Connections/RelayTunnelConnector.cs
ts/src/connections/relayTunnelConnector.ts
ts/src/connections/sshHelpers.ts

Fix for https://github.com/microsoft/basis-planning/issues/581
Normally nginx choses another healthy pod when it encounters 503. However, if there are no other pods, it returns 503 to the client. This rare case may happen when the cluster recovers from a failure and the nginx controller has started but Relay service has not yet.

Reconnect tunnel client on 503

---

cs/build/build.props

Reverts microsoft/dev-tunnels#164
There's a stack overflow in the SSH lib that _sometimes_ causes tunnel connection tests to fail. It wasn't caught by PR builds, but failed in CI builds. I'm reverting the update until I can resolve the issue.

Revert "Update to latest SSH package"

---

cs/build/build.props
cs/src/Connections/TunnelRelayTunnelHost.cs
ts/package-lock.json
ts/package.json
ts/src/connections/tunnelRelayTunnelHost.ts

I [reverted](https://github.com/microsoft/dev-tunnels/pull/166) the [previous attempt](https://github.com/microsoft/dev-tunnels/pull/164) at updating the SSH package, because it resulted in an occasional stack overflow in tests. I found that the bug was in this repo, and this change includes the fix.

Update SSH package, fix reconnect condition

---

java/src/main/java/com/microsoft/tunnels/websocket/WebSocketSession.java

Fixes Customer issue
- Adds suspend and resume read functions to java websocketsession implementation
Note: these functions don't do anything in the NettyIoSession but should prevent errors from being thrown if they are referenced

A suspend and resume reads to java

---

cs/src/Contracts/TunnelConstraints.cs

Fixes issue where tunnels ending in -inspect can get confused with inspection service routing
- Adds restriction that tunnel names cannot end in -inspect as this will be used by the inspection urls
- If name is rejected, reason will be shown in CLI (separate PR)

Restrict tunnel names ending in -inspect

---

ts/src/connections/tunnelRelayTunnelHost.ts

Do not trace error for expected cancellations during Tunnel Relay tunnel host disposal.
Fixes [#609](https://github.com/microsoft/basis-planning/issues/609)
- Do not trace error for expected cancellation during Tunnel Relay tunnel host disposal

Fix TunnelRelayTunneHost dispose error

---

.pipelines/cs-build-steps.yaml
.pipelines/cs-ci-build.yaml
.pipelines/cs-pr-build.yaml

Our build pipeline failed to publish the new .snupkg files to nuget.org because it was using an old version of the nuget CLI. This will install an appropriate version of nuget and prepend it to the build machine's PATH.
Here are some lines from our build pipeline output.
```
Detected NuGet version 4.1.0.2450 / 4.1.0
...
##[error]The nuget command failed with exit code(1) and error(System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Snupkg upload failed. Please use latest NuGet clients (v 4.9.0 or above) and a V3 endpoint to push Symbol packages. For details, refer https://docs.microsoft.com/nuget/create-packages/symbol-packages-snupkg).
```

Specify nuget version 6.4.x in build pipeline

---

.pipelines/cs-ci-build.yaml

This PR fixes a bug, which causes duplicate attempts to publihs snupkg to Nuget. It reverts one line of [this PR](https://github.com/microsoft/dev-tunnels/commit/5f128d4b193d0320204a86b4ed0a2bc84390e96d).
See this related PR for context: https://github.com/microsoft/dev-tunnels-ssh/pull/31

remove snupkg from nuget publish step

---

cs/tools/TunnelsSDK.Generator/RustContractWriter.cs
rs/src/contracts/tunnel_access_control_entry.rs
rs/src/contracts/tunnel_access_scopes.rs
rs/src/contracts/tunnel_authentication_schemes.rs
rs/src/contracts/tunnel_constraints.rs
rs/src/contracts/tunnel_header_names.rs
rs/src/contracts/tunnel_protocol.rs
rs/src/management/http_client.rs

The latest Rust code was not compiling. Fixes that.
It'd be nice to add CI for Rust to avoid these kinds of breakages; e.g. it looks like at one point new code was added that didn't compile.

fix: rust build errors

---

ts/src/connections/sshHelpers.ts
ts/src/connections/tunnelClientBase.ts
ts/src/connections/tunnelRelayTunnelHost.ts

TS client and server code should be using `SshHelpers.createSshSession()` to get correct and consistent SSH algorithm configuration. In particular, `diffie-hellman-group16-sha512` is _not_ configured because the JS implementation can be slow in browsers. This shared helper was used originally, then was lost after host & client code was refactored to support reconnections.

Fix TS SSH sesion config

---

cs/build/build.props

Updates the SSH package consumed by Microsoft.DevTunnels.Connections so that published symbols are available to consumers.

Update Dev Tunnels SSH package

---

rs/CONTRIBUTING.md
rs/Cargo.lock
rs/Cargo.toml
rs/src/contracts/tunnel.rs
rs/src/contracts/tunnel_port.rs
rs/src/management/http_client.rs

Cleans up the Rust http_client
- Ensure that the rust SDK version is included in the user agent header
- Fix a rust bug that appended `?` to URLs, even when there is no query string

Fix rust agent header and empty query string

---

cs/src/Connections/IRelayClient.cs
cs/src/Connections/ITunnelRelayStreamFactory.cs
cs/src/Connections/TunnelRelayStreamFactory.cs
cs/src/Connections/TunnelRelayTunnelClient.cs
cs/src/Connections/TunnelRelayTunnelHost.cs
cs/src/Connections/WebSocketStream.cs
cs/test/TunnelsSDK.Test/Mocks/MockTunnelRelayStreamFactory.cs

This change adds support for negotiating the relay connection protocol version via the websocket subprotocol. Actual implementation of the v2 protocol is not included; that will come later.
- Update `TunnelRelayStreamFactory` to support _requesting_ multiple protocols and _returning_ the single negotiated protocol selected by the service.
- Add a public `ConnectionProtocol` property to tunnel host and client. (This property will primarily be used by the relay service to follow a different code path depending on the protocol version.)
- Log the negotiated connection protocol in the verbose log.

Negotiate relay connection protocol version

---

java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java

Updating Java SDK to support local testing with http://localhost:9900 service url.
We found that this is not working while testing the fix for JetBrains [issue](https://github.com/microsoft/basis-planning/issues/685)

Support local testing for Java SDK

---

cs/build/build.props

Bumping up SSH package version to include IgnoreMessage [change](https://github.com/microsoft/dev-tunnels-ssh/pull/34). This is for JetBrains [issue](https://github.com/microsoft/basis-planning/issues/685) and while testing the [change](https://devdiv.visualstudio.com/OnlineServices/_git/tunnels/pullrequest/452476) found that CLI requires SDK to use the SSH [fix](https://github.com/microsoft/dev-tunnels-ssh/pull/34).

Update SSH package version to include IgnoreMessage change

---

.vscode/settings.json
rs/Cargo.lock
rs/Cargo.toml
rs/src/connections/errors.rs
rs/src/connections/relay_tunnel_host.rs
rs/src/connections/ws.rs

Tungstenite [doesn't support proxies](https://github.com/snapview/tungstenite-rs/issues/177) automatically like reqwest does, so this adds support for them in the SDK.
Request on VS Code's side: https://github.com/microsoft/vscode/issues/169333

rust: add support for HTTPS_PROXY

---

cs/src/Contracts/TunnelPort.cs
go/tunnels/tunnel_port.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelPort.java
rs/src/contracts/tunnel.rs
rs/src/contracts/tunnel_port.rs
ts/src/contracts/tunnelPort.ts

Fixes https://github.com/microsoft/basis-planning/issues/715
- Adds list of inspection URIs to tunnel port contract

Add inspection uri to port contract

---

rs/Cargo.toml

Previously we vendored openssl in vscode, which hid this bug: we also need to explicitly turn `native-tls` support on in Tungstenite for TLS to work at all.

rs: fix tls connections not working unless openssl was vendored

---

cs/src/Connections/ITunnelClient.cs
cs/src/Connections/MultiModeTunnelClient.cs
cs/src/Connections/RetryTcpListenerFactory.cs
cs/src/Connections/TunnelClient.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs
ts/package-lock.json
ts/src/connections/multiModeTunnelClient.ts
ts/src/connections/retryTcpListenerFactory.ts
ts/src/connections/tunnelClient.ts
ts/src/connections/tunnelClientBase.ts
ts/test/tunnels-test/connectTests.ts
ts/test/tunnels-test/tunnelHostAndClientTests.ts

Enables applications to override the default local interface (127.0.0.1) used by the tunnel client to listen for forwarded port connections.

Add tunnel client local address property

---

cs/build/build.props
cs/src/Connections/Messages/PortRelayConnectMessage.cs
cs/src/Connections/Messages/PortRelayRequestMessage.cs
cs/src/Connections/RelayTunnelConnector.cs
cs/src/Connections/SessionPortKey.cs
cs/src/Connections/TunnelClient.cs
cs/src/Connections/TunnelConnection.cs
cs/src/Connections/TunnelHost.cs
cs/src/Connections/TunnelRelayTunnelClient.cs
cs/src/Connections/TunnelRelayTunnelHost.cs
cs/src/Management/TunnelAccessTokenProperties.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs
ts/package-lock.json
ts/package.json
ts/src/management/tunnelAccessTokenProperties.ts

This change implements the host and client SDK parts of the V2 relay connection protocol, for C# only. Ports to other SDK languages will come in separate PR(s).
For design & background info, refer to the [ADR](https://github.com/microsoft/basis-planning/blob/main/ADRs/0029-tunnel-connection-protocol.md).
Host and client SDKs have simultaneous support for V1 and V2 protocols; they prefer V2 but allow the service to choose V1 via the websocket subprotocol negotiation. So the V2 protocol is not used unless the service enables it, and that is currently conditional on a feature flag.
SDK client changes:
- The client configures the SSH session to support negotiation of no encryption. Since that session is not E2E encrypted, it's more efficient to skip it. (V2 E2E encryption will be added back …

Connection protocol v2 SDK implementation (C#)

---

cs/build/build.props

Fixes # https://github.com/microsoft/basis-planning/issues/55
This bumps the version of the SSH dependencies, which have a symbols that expire after 3 years instead of 30 days.

Bump the version of ssh dependency

---

cs/src/Connections/TunnelClient.cs
cs/src/Connections/TunnelRelayTunnelClient.cs

Tunnel hosts have already been publishing their SSH public keys to the management service along with the other tunnel endpoint info. So the missing piece is for tunnel clients to verify the host key when authenticating the SSH session.

Verify host public keys when connecting client

---

cs/build/build.props

Update SSH nuget package version to pick up the fix for concurrent session requests: https://github.com/microsoft/dev-tunnels-ssh/pull/51
The bug was (rarely) causing port number mix-ups when forwarding multiple ports in a tunnel.

Update SSH nuget package version

---

rs/Cargo.lock
rs/Cargo.toml

Chrono by default depends on an old version of 'time' which was a low severity dependabot alert. It's not actually needed for the use case in the SDK.

rust: disable default features in chrono

---

cs/src/Contracts/NamedRateStatus.cs
cs/src/Contracts/RateStatus.cs
go/tunnels/resource_status.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/NamedRateStatus.java
java/src/main/java/com/microsoft/tunnels/contracts/RateStatus.java
rs/src/contracts/mod.rs
rs/src/contracts/named_rate_status.rs
rs/src/contracts/rate_status.rs
ts/src/contracts/namedRateStatus.ts
ts/src/contracts/rateStatus.ts

- Add a `NamedRateStatus` contract, which is a `RateStatus` with a string name attached.
- Add a note in the `RateStatus` docstring that the expected unix time is in seconds.

Add NamedRateStatus

---

cs/src/Contracts/ResourceStatus.cs
go/tunnels/resource_status.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/ResourceStatus.java
rs/src/contracts/resource_status.rs
ts/src/contracts/resourceStatus.ts

- Adds an optional `LimitSource`  property to `ResourceStatus`, so that we can indicate when a limit has been overridden as a result of applied User Limits.

Add a LimitSource property to ResourceStatus

---

cs/src/Management/ITunnelManagementClient.cs
cs/src/Management/TunnelManagementClient.cs
cs/test/TunnelsSDK.Test/Mocks/MockTunnelManagementClient.cs

- This adds a method to the ITunnelManagementClient to fetch user limits from the `/userlimits` endpoint.

Add user limits to CS SDK

---

rs/src/management/http_client.rs

- This allows consumers of the Rust SDK to check user limits by calling the /userlimits API endpoint

Add user limits to Rust SDK

---

java/src/main/java/com/microsoft/tunnels/management/ITunnelManagementClient.java
java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java

- Adds ability to query user limits to the Java SDK
I tested locally by adding a unit test and supplying a bearer token. I did not check in the test because the tests appear to use the live service endpoint (as opposed to a mock object), and limit values do not currently exist for test accounts.

Add user limits to Java SDK

---

cs/src/Contracts/TunnelConstraints.cs
cs/test/TunnelsSDK.Test/TunnelConstraintsTests.cs
go/tunnels/tunnel_constraints.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelConstraints.java
rs/src/contracts/tunnel_constraints.rs
ts/src/contracts/tunnelConstraints.ts

Fixes # https://github.com/microsoft/basis-planning/issues/925
- Allow empty string in tunnel name & domain pattern
- Tested consuming the change in the CLI

[Contracts] Allow empty string in name & domain validation.

---

cs/src/Contracts/TunnelAuthenticationSchemes.cs
go/tunnels/tunnel_authentication_schemes.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelAuthenticationSchemes.java
rs/src/contracts/tunnel_authentication_schemes.rs
ts/src/contracts/tunnelAuthenticationSchemes.ts

- Adds tunnel plan auth scheme 
-
-

Add tunnelplan Auth Scheme

---

cs/src/Connections/TunnelRelayTunnelHost.cs

Fixes #840
- This Pr  makes some ClientSSH logs verbose. So will be cleaner for non-verbose logs in CLI. 
- Session closed and cancelled information should start with Client SSH for consistency

change Client ssh info logs  to verbose.

---

ts/src/management/tunnelManagementHttpClient.ts
ts/test/tunnels-test/tunnelManagementTests.ts

The Codespaces web client needs to be able to call the SDK from within a service worker and since `axios` isn't [supported in workers](https://github.com/axios/axios/issues/1219), a custom adapter (such as [this one](https://www.npmjs.com/package/@vespaiach/axios-fetch-adapter)) is needed to use `fetch` to avoid the `TypeError: adapter is not a function` error. This change allows an optional adapter to be passed into the `TunnelManagementHttpClient` that will be used when making HTTP requests with `axios`.

Allow optional `axios` adapter in `TunnelManagementHttpClient`

---

cs/src/Connections/ConnectionStatus.cs
cs/src/Connections/ITunnelHost.cs
cs/src/Connections/TunnelClient.cs
cs/src/Connections/TunnelConnection.cs
cs/src/Connections/TunnelRelayTunnelClient.cs
cs/src/Connections/TunnelRelayTunnelHost.cs
cs/test/TunnelsSDK.Test/Mocks/MockTunnelManagementClient.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs
ts/src/connections/connectionStatus.ts
ts/src/connections/relayTunnelConnector.ts
ts/src/connections/tunnelClientBase.ts
ts/src/connections/tunnelConnectionSession.ts
ts/src/connections/tunnelConnector.ts
ts/src/connections/tunnelHostBase.ts
ts/src/connections/tunnelRelaySessionClass.ts
ts/src/connections/tunnelRelayTunnelClient.ts
ts/src/connections/tunnelRelayTunnelHost.ts
ts/src/connections/tunnelSession.ts
ts/src/connections/tunnelSshSessionClass.ts
ts/src/management/tunnelAccessTokenProperties.ts
ts/test/tunnels-test/connection.ts
ts/test/tunnels-test/mocks/mockTunnelManagementClient.ts
ts/test/tunnels-test/mocks/mockTunnelRelayStreamFactory.ts
ts/test/tunnels-test/testTunnelRelayTunnelClient.ts
ts/test/tunnels-test/tunnelHostAndClientTests.ts

Fix for [#979](https://github.com/microsoft/basis-planning/issues/979).
When the client fails to authenticate the host SSH session, it must refresh the tunnel from the service and get the new endpoint public key if possible, then retry.
* Add new connection status when the client refreshes the tunnel to get the new host public keys.
* Refactor various places where the tunnel object properties are used for tunnel host and client.
* Make authentication callback in the client handle host public key mismatch by fetching the tunnel and retrying.
* Add unit tests.
* Change how `httpAgent` is passed to ts SDK clients.
* Fix ts mock tunnel management client getTunnel() not returning the right tunnel.
* Fix ts SDK unit tests incorrectly using v2 connection protocol.

C# and node client can refresh host public keys on connection.

---

cs/src/Management/ITunnelManagementClient.cs
cs/src/Management/TunnelManagementClient.cs
cs/src/Management/TunnelPlanTokenProperties.cs
cs/test/TunnelsSDK.Test/Mocks/MockTunnelManagementClient.cs
ts/src/management/tunnelManagementHttpClient.ts
ts/src/management/tunnelPlanTokenProperties.ts

- Adds option for list tunnels that only lists tunnels owned by the user instead of all tunnels in the tunnel plan
- If a tunnel plan is used for auth, always use a cluster specific url

Add ownedTunnelsOnly option and tunnelPlan redirection

---

cs/src/Connections/TunnelConnection.cs
cs/src/Management/TunnelManagementClient.cs
cs/test/TunnelsSDK.Test/TunnelManagementClientTests.cs
ts/src/connections/tunnelConnectionSession.ts
ts/src/management/tunnelManagementHttpClient.ts
ts/test/tunnels-test/tunnelManagementTests.ts

When calling management APIs like `getTunnel()` or `updateTunnel()`, if the input Tunnel object has one or more tokens inn its `accessTokens` property, those tokens should be preserved in the returned Tunnel object if not refreshed by the request.

Preserve access tokens when refreshing tunnel

---

rs/src/connections/relay_tunnel_host.rs

ipv6-only services are getting more common, especially with a Node 18
change that causes it to listen on ipv6 by default on most enabled
networks. In advance of releasing local forwarding for vscode, I think
we should support this.
This PR supports local ipv6 forwarding by reaching out to both the ipv6
and ipv4 interfaces by default, and using whichever one (if any)
accepts the TCP connection first.

rs: support ipv6 port-forwarded services

---

cs/src/Contracts/Tunnel.cs
cs/src/Management/TunnelManagementClient.cs
go/tunnels/tunnel.go
java/src/main/java/com/microsoft/tunnels/contracts/Tunnel.java
rs/src/contracts/tunnel.rs
ts/src/contracts/tunnel.ts

Fixes #
For the new feature `CustomTunnelExpiration` we are adding a property to the Tunnel object that stores the value a user inputs if they want a custom tunnel expiration. This is currently being added as a command line option in both `create` and `host` in tunnels, and these are the associated SDK changes needed to make sure that the value the user specifies in the CLI is reflected when the tunnel is created

Custom expiration cli changes

---

cs/src/Management/TunnelAccessControlExtensions.cs
cs/test/TunnelsSDK.Test/TunnelAccessTests.cs

The `IsAllowed()` extension method for `TunnelAccessControl` was not handling deny rules correctly, and was ignoring the inverse flag. This fixes it to match the logic used by service authorization checks.
Note there is no equivalent for this method in the SDKs for languages other than C#.

Fix access control IsAllowed logic

---

cs/build/build.props

Fixes https://github.com/microsoft/basis-planning/issues/733
- Insert NuGet SSH v3.11.28 that has two fixes for memory leaks in SSH API objects.

Insert NuGet SSH v3.11.28

---

cs/src/Management/TunnelExtensions.cs
cs/src/Management/TunnelManagementClient.cs

Since the Relay needs to make calls to the service we need to support some tunnelV2 calls in the SDK for now. These will be deleted when the SDKS moves fully to TunnelV2

Add extensions needed for ControlPlanManagementClient in relay

---

cs/src/Connections/ITunnelClient.cs
cs/src/Connections/ITunnelConnector.cs
cs/src/Connections/ITunnelHost.cs
cs/src/Connections/MultiModeTunnelClient.cs
cs/src/Connections/MultiModeTunnelHost.cs
cs/src/Connections/RelayTunnelConnector.cs
cs/src/Connections/TunnelClient.cs
cs/src/Connections/TunnelConnection.cs
cs/src/Connections/TunnelConnectionOptions.cs
cs/src/Connections/TunnelHost.cs
cs/src/Connections/TunnelRelayTunnelClient.cs
cs/src/Connections/TunnelRelayTunnelHost.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs
ts/src/connections/multiModeTunnelClient.ts
ts/src/connections/multiModeTunnelHost.ts
ts/src/connections/relayTunnelConnector.ts
ts/src/connections/tunnelClient.ts
ts/src/connections/tunnelClientBase.ts
ts/src/connections/tunnelConnectionBase.ts
ts/src/connections/tunnelConnectionOptions.ts
ts/src/connections/tunnelConnectionSession.ts
ts/src/connections/tunnelConnector.ts
ts/src/connections/tunnelHost.ts
ts/src/connections/tunnelHostBase.ts
ts/src/connections/tunnelRelaySessionClass.ts
ts/src/connections/tunnelSession.ts
ts/test/tunnels-test/connectTests.ts
ts/test/tunnels-test/tunnelHostAndClientTests.ts

- Introduce `TunnelConnectionOptions` as an optional parameter to the client and host `Connect` API.
- It allows the application to specify retry and reconnect behavior, and will make it easier to add more connection options in the future without breaking changes.
- Rename host's `Start` to `Connect` for consistency.
- `Start` is still available for now, but marked as obsolete/deprecated.
- Fix and test issues related to retry and cancellation of both C# and TS connections.
- Add missing cancellation token parameter to TS `connect`.
- Ensure the correct exception type is thrown if the token is cancelled or the client/host is disposed during the connection or retries.
- Ensure the client or host instance can be re-used after a failed or cancelled connection attempt.
Above changes apply …

Improve host & client connect options and cancellation

---

go/tunnels/client.go
go/tunnels/client_test.go
go/tunnels/tunnels.go

Uses the TCP listener passed into the `ConnectToForwardedPort` function to actually connect to the port via a local TCP port. This is the same logic that is used by the [GH CLI](https://github.com/cli/cli/blob/c5f88bb551e22b04a3799561f3abea4892012eff/pkg/liveshare/port_forwarder.go#L78C27-L78C44) which is what much of this connection code seems to be based on.
cc. @jfullerton44

Fix connecting to local TCP port in Go SDK

---

cs/src/Contracts/TunnelPortV2.cs
go/tunnels/tunnel_port_v2.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelPortV2.java
rs/src/contracts/tunnel_port_v2.rs
ts/src/contracts/tunnelPortV2.ts

Fixes #
- Updates V2 ports to use labels instead of tags
-
-

Update V2 Ports to Labels instead of Tags

---

go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java
ts/src/management/tunnelManagementHttpClient.ts

- For the custom expiration feature, you can set the custom expiration via the SDK for cs. This PR lets you set the expiration via ts, java, and go SDK

Add custom expiration to ts , java, and go tunnel sdk creation

---

cs/src/Contracts/TunnelEndpoint.cs
go/tunnels/tunnel_endpoint.go
go/tunnels/tunnels.go
rs/src/contracts/tunnel_endpoint.rs
ts/src/contracts/tunnelEndpoint.ts

Fixes #
- This allows the endpoint id to be nullable to continue to support older api-versions
-
-

Allow endpoint id to be nullable

---

cs/src/Contracts/TunnelListByRegion.cs
go/tunnels/tunnel_list_by_region.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelListByRegion.java
rs/src/contracts/tunnel_list_by_region.rs
ts/src/contracts/tunnelListByRegion.ts

Fixes #
- Return V2 Tunnel in region list response 
-
-

Return V2 tunnel in region list response

---

cs/src/Contracts/TunnelAccessControlEntry.cs
go/tunnels/tunnel_access_control_entry.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelAccessControlEntry.java
rs/src/contracts/tunnel_access_control_entry.rs
ts/src/contracts/tunnelAccessControlEntry.ts

Fixes #
- These are the SDK changes needed to add expiration dates to access control entries. This change can be used in the different SDKs by adding the `expiration` property to their `TunnelAccessControlEntry` objects

Access Control Entry Expiration

---

cs/src/Management/TunnelManagementClient.cs

- Fixes bug where functionality would be broken when api-version was not set

Add default api-version in C#

---

cs/src/Management/TunnelManagementClient.cs

Fixes #
- Fixes issue where allowNotFound was not being set properly for the new list operations. This is only a C# issue
-
-

Fix error handling for list in C#

---

cs/src/Management/TunnelManagementClient.cs
go/tunnels/manager.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/management/TunnelManagementClient.java
ts/src/management/tunnelManagementHttpClient.ts

Fixes #
- Adds query params to force a tunnel update or tunnel create that will be added to the service in a different PR
- Fixes issue in typescript where last retry message would get a clusterId missing error
-

Add forceCreate and forceUpdate query params

---

cs/test/TunnelsSDK.Test/Extensions/TunnelConnectionExtensions.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs

The issue was that the test was asynchronously waiting for `Connecting` connection status and then asserted disconnect exception while reconnection run in parallel and might have cleared up the disconnect exception.
The fix is to assert the disconnect exception in `ConnectionStatusChanged` event handler.

Fix flaky ConnectRelayClientToHostAndReconnectHost test

---

cs/src/Management/DevTunnels.Management.csproj
cs/src/Management/PolicyProvider.cs
cs/src/Management/RegistryTools.cs
cs/src/Management/TunnelManagementClient.cs

Fixes # https://github.com/orgs/microsoft/projects/115/views/18?pane=issue&itemId=43806545 
- Read policies from windows registry and add them to the request header. 
- Updated header:

Add policies property to tunnelservice request header on C#

---

ts/package-lock.json
ts/package.json
ts/src/management/package.json
ts/src/management/tunnelManagementHttpClient.ts

Bumps axios to version `1.6.2` in the TS SDK to resolve [CVE-2023-45857](https://www.cve.org/CVERecord?id=CVE-2023-45857). I am not aware of any other breaking changes, but if there are any concerns, please let me know/how I can test properly to make sure everything still works as expected.
We can close https://github.com/microsoft/dev-tunnels/pull/350 after this merges.

Bump axios to version `1.6.2` to resolve security vulnerability

---

cs/src/Connections/ITunnelClient.cs
cs/src/Connections/MultiModeTunnelClient.cs
cs/src/Connections/PortForwardingEventArgs.cs
cs/src/Connections/TunnelClient.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs
ts/src/connections/index.ts
ts/src/connections/multiModeTunnelClient.ts
ts/src/connections/portForwardingEventArgs.ts
ts/src/connections/tunnelClient.ts
ts/src/connections/tunnelRelayTunnelClient.ts
ts/test/tunnels-test/connectTests.ts
ts/test/tunnels-test/tunnelHostAndClientTests.ts

Normally a tunnel client will forward all ports requested by the host. However in some scenarios it's useful for a client to be able to selectively decline to forward some port numbers. This change adds a `TunnelClient.PortForwarding` event with a `Cancel` property. The event notifies the client application when a port is about to be forwarded as requested by the host and allow cancellation of that request.

Allow client app to cancel fwd of specific ports

---

cs/src/Management/ManagementApiVersions.cs
cs/src/Management/TunnelManagementClient.cs
ts/src/management/managementApiVersions.ts
ts/src/management/tunnelManagementHttpClient.ts
ts/test/tunnels-test/connection.ts
ts/test/tunnels-test/host.ts
ts/test/tunnels-test/tunnelManagementTests.ts

Fixes #
- Adds an enum for api versions in C# and TS SDKs
-
-

Add enum for Api Version in C# and TS

---

cs/src/Management/TunnelManagementClient.cs

Fixes an issue where the api-version param was not included in check-name requests

Add api-version to check-name requests

---

rs/src/management/http_client.rs
rs/src/management/policy_provider.rs

Fixes #388
- Avoids noisy error logging if no access policies are configured
- Fixes a compilation warning, and generate the user agent string in a slightly DRY-er way

rs: fix error logs and compilation warning on non-windows

---

.github/workflows/rust.yml
rs/src/connections/relay_tunnel_host.rs
rs/src/connections/ws.rs
rs/src/contracts/tunnel.rs
rs/src/contracts/tunnel_access_control_entry.rs
rs/src/contracts/tunnel_constraints.rs
rs/src/contracts/tunnel_port.rs
rs/src/management/http_client.rs
rs/src/management/tunnel_request_options.rs

Fixes #
- Adds endpoint connection mode query  param to fix issue where endpoint is always returned as local network
-
-

Add endpoint connection mode query param

---

rs/src/connections/errors.rs
rs/src/connections/ws.rs

Rather than only host:port
For microsoft/vscode#201417
- HTTPS_PROXY may be given as a URI rather than just host:port. Doing so is rather extraneous since only the host and port are used, but handle parsing it anyway.

rs: allow parsing proxies given as full URIs

---

rs/src/management/policy_provider.rs

rs: fix policy registry key name

---

cs/src/Management/TunnelManagementClient.cs

- Removed redundant response handling code for enterprise policies.

Update response handling for enterprise policies

---

cs/src/Management/TunnelManagementClient.cs
cs/test/TunnelsSDK.Test/TunnelManagementClientTests.cs
ts/src/management/tunnelManagementHttpClient.ts
ts/test/tunnels-test/tunnelManagementTests.ts

When handling a 4xx error response from a tunnel management API request, check for the absence `X-Served-By` response header to detect when the error was likely caused by a firewall intercepting the request.

Detect 4xx error response from firewall

---

.github/workflows/codeql-analysis.yml

Fixes the broken CodeQL action: https://github.com/microsoft/dev-tunnels/actions/runs/9455978672
Related Blogs:
- https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
- https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

Upgrade CodeQL version from v1 to v3

---

cs/build/build.props
cs/test/TunnelsSDK.Test/TcpListeners.cs
cs/test/TunnelsSDK.Test/TcpUtils.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs
cs/test/TunnelsSDK.Test/XunitTraceListener.cs

Fixes [#1618](https://github.com/devdiv-microsoft/basis-planning/issues/1618).
- Insert SSH 3.11.41 that has the fix.
- Add a unit test for client connecting to host when the tunnel has multiple port. 
- Add more logging to unit tests.
Only C# SDK is updated.

Insert SSH 3.11.41, add more unit tests and logging to tests

---

cs/src/Management/TunnelManagementClient.cs
cs/src/Management/UnauthorizedAccessExceptionExtensions.cs
cs/test/TunnelsSDK.Test/TunnelManagementClientTests.cs

This change enables applications to programmatically detect when an `UnauthorizedAccessException` was thrown due to a specific policy violation.

Add failed policy requirement names to UnauthorizedAccessException

---

README.md
cs/build/build.props
cs/src/Connections/IRelayClient.cs
cs/src/Connections/ITunnelClient.cs
cs/src/Connections/ITunnelHost.cs
cs/src/Connections/RelayTunnelConnector.cs
cs/src/Connections/SshKeepAliveFailureEventArgs.cs
cs/src/Connections/TunnelClient.cs
cs/src/Connections/TunnelConnection.cs
cs/src/Connections/TunnelConnectionOptions.cs
cs/src/Connections/TunnelRelayConnection.cs
cs/src/Connections/TunnelRelayTunnelClient.cs
cs/src/Connections/TunnelRelayTunnelHost.cs

Implement support for keep alive messages in SSH layer. Providing `KeepAliveIntervalInSeconds` to the SDK will send keep-alive messages to the server at the specified interval. And calls the `KeepAliveRequestFailed` event if the server does not respond to the keep-alive message.

Implement ssh keep-alive for Tunnels C# SDK

---

cs/src/Contracts/TunnelOptions.cs
rs/src/contracts/tunnel_options.rs

The two new CORS-related options `IsCrossSiteAuthenticationEnabled` and `IsPartitionedSiteAuthenticationEnabled` can be applied to tunnel and/or to specific port(s) of a tunnel. The properties should be nullable so that a null value for a port means it will inherit the setting from the tunnel (if non-null) while a non-null true or false for a port would override any tunnel-level setting.
The properties were already nullable in the auto-generated TypeScript contract, so there are no changes there.

Fix nullability for tunnel CORS options

---

cs/src/Connections/SshSessionExtensions.cs
cs/src/Connections/TunnelClient.cs
cs/src/Connections/TunnelConnection.cs
cs/src/Connections/TunnelRelayConnection.cs
cs/src/Connections/TunnelRelayTunnelHost.cs
cs/src/Connections/WebSocketStream.cs
ts/src/connections/tunnelConnectionSession.ts
ts/src/connections/tunnelRelayTunnelHost.ts

Add host and client session IDs to connection events reporting. This allows for correlation of connection events during a session lifetime and correlation of host and client sessions. Also report the websocket HTTP request ID for the connection (in C# only; the header is not available in JS).

Add session ID properties to connection events reporting
