microsoft/dev-tunnels

cs/src/Contracts/ResourceStatus.cs
cs/src/Contracts/TunnelAccessControl.cs

- `ResourceStatus` serialization/deserialization could infinitely recurse in some cases. There's not a simple way to ask the serializer to do default serialization (without the converter to avoid recursing), so it takes a little more code to handle it explicitly while respecting other serializer options.
- After reviewing other converter classes, I updated the `TunnelAccessControl` converter to better respect serializer options.
- Implicit conversions between `ResourceStatus` and `ulong` simplify status-reporting and testing code.

Fix ResourceStatus serialization bug

---

ts/src/management/tunnelManagementHttpClient.ts

TS contract interfaces declare some properties as `Date` type. I noticed they are actually getting deserialized as strings (which makes sense). There's no easy way to define custom deserializers in TS/JS. So I added some code to fix up those properties in each API that can return time. It does mean we'll have to update that code if we add more `Date` properties to any contracts.

Fix date properties after deserializing in TS SDK

---

cs/src/Contracts/TunnelAccessControlEntry.cs
cs/src/Contracts/TunnelAccessControlEntryType.cs
go/tunnels/tunnel_access_control_entry.go
go/tunnels/tunnel_access_control_entry_type.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelAccessControlEntry.java
java/src/main/java/com/microsoft/tunnels/contracts/TunnelAccessControlEntryType.java
ts/src/contracts/tunnelAccessControlEntry.ts
ts/src/contracts/tunnelAccessControlEntryType.ts

Adds a service tag provider to the IP address range access control entry type.

Add service tag access control entry

---

cs/build/build.props

Fixes: https://github.com/microsoft/basis-planning/issues/452

Update SSH package version

---

cs/src/Contracts/TunnelHeaderNames.cs
go/tunnels/tunnel_header_names.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelHeaderNames.java
rs/src/contracts/tunnel_header_names.rs
ts/src/contracts/tunnelHeaderNames.ts

This adds a header that can be sent with web forwarding requests to skip the anti phishing page

Add antiphishing header

---

cs/build/build.props

Picking up the fix in https://github.com/microsoft/dev-tunnels-ssh/pull/15

Update to latest SSH package

---

cs/src/Management/TunnelRequestOptions.cs
go/tunnels/request_options.go
java/src/main/java/com/microsoft/tunnels/management/TunnelRequestOptions.java
rs/src/management/http_client.rs
rs/src/management/tunnel_request_options.rs
ts/src/management/tunnelManagementHttpClient.ts
ts/src/management/tunnelRequestOptions.ts

Fixes https://github.com/microsoft/basis-planning/issues/611

Add IncludeAccessControl request option

---

java/src/main/java/com/microsoft/tunnels/websocket/WebSocketSession.java

- Implements the suspendRead and ResumeRead functions in WebSocketSession using a semaphore

Implement suspendRead and resumeRead in Java

---

ts/package-lock.json
ts/package.json
ts/src/connections/LICENSE
ts/src/connections/package.json
ts/src/contracts/LICENSE
ts/src/contracts/package.json
ts/src/management/LICENSE
ts/src/management/package.json

Fixes CG alert https://devdiv.visualstudio.com/OnlineServices/_componentGovernance/tunnels/alert/7324807?typeId=14091026
- Add "license" and "author" fields to ts `package.json`
- Add LICENSE file to ts package folders - copied form the parent ts folder.
- Update package-lock.json

Add license, author, and LICENSE file to ts packages

---

cs/build/build.props

Fixes [#769](https://github.com/microsoft/basis-planning/issues/769)
Insert DevTunnels SSH NuGet package v3.11.2

Use DevTunnels SSH NuGet package v3.11.2

---

ts/src/connections/tunnelRelayTunnelHost.ts

- Fixes issue where timing issue can cause error with promise rejection

Update cancellation to fix timing error

---

cs/src/Connections/TunnelRelayTunnelHost.cs

This is a small optimization that can make client connection setup a little faster, particularly when there are a lot of ports forwarded over a high-latency connection.
The change is only in the C# SDK, because the TS SSH lib doesn't support concurrent session requests. However it can receive and handle those concurrent requests (sequentially); I confirmed there is no compatibility here.
(The C# SDK didn't support concurrent requests either at the time this code was originally written. That support was added more recently.)

Send port-forward request messages concurrently

---

ts/src/connections/tunnelConnectionSession.ts

Fix for [#806](https://github.com/microsoft/basis-planning/issues/806)
When refreshing tunnel access token, `TunnelConnectionSession.getFreshAccessToken()` calls `tunnelManager` if it was set to fetch the current tunnel using `this.tunnel` property. If the fetched tunnel has a valid access token, then refresh succeeds. However the fetched tunnel may not have the access token, and so a valid access token on `this.tunnel` object may be ignored.
The fix is to use the access token from `this.tunnel` if the fetched tunnel doesn't have one.
CS SDK has been fixed with https://github.com/microsoft/dev-tunnels/pull/216

Fix TunnelConnectionSession.getFreshAccessToken in ts SDK

---

ts/src/contracts/index.ts
ts/src/management/tunnelManagementClient.ts
ts/src/management/tunnelManagementHttpClient.ts
ts/test/tunnels-test/mocks/mockTunnelManagementClient.ts
ts/test/tunnels-test/tunnelManagementTests.ts

- Adds ability to query user limits to the TS SDK
In addition to the included unit test, I tested this out by consuming it in a local node project.

Add User limits to TS SDK

---

go/tunnels/examples/example.go
go/tunnels/manager.go
go/tunnels/tunnels.go

- Adds the ability to query user limits to the Go SDK
Tested using the example.go sample program.

Add user limits to Go SDK

---

ts/package-lock.json
ts/package.json

Fixes https://teams.microsoft.com/l/message/19:aLsMyfH4tOiPVswuVJAH4qvhOu8INKhMddvRQs7cwMs1@thread.tacv2/1689283586604?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=9b17b49d-aeac-4d9e-8ce8-b5a7e03b6e27&parentMessageId=1689283586604&teamName=Dev%20Tunnels%20Partners&channelName=General&createdTime=1689283586604&allowXTenantAccess=false
Updates ssh package to latest published version

Update ssh versions in TS package

---

cs/src/Contracts/TunnelConstraints.cs
java/src/main/java/com/microsoft/tunnels/contracts/TunnelConstraints.java
java/src/main/java/com/microsoft/tunnels/contracts/TunnelConstraintsStatics.java

- Adds validation method that checks if tunnel id is valid for either version
-
-

Add validation for both tunnel id forms

---

cs/src/Contracts/TunnelConstraints.cs
go/tunnels/tunnel_constraints.go
go/tunnels/tunnels.go
java/src/main/java/com/microsoft/tunnels/contracts/TunnelConstraints.java
rs/src/contracts/tunnel_constraints.rs
ts/src/contracts/tunnelConstraints.ts

Add E to tunnelId Chars

---

rs/Cargo.lock
rs/Cargo.toml
rs/src/connections/relay_tunnel_host.rs

Tested this in the VS Code CLI and we're good.
Also starts adding an ID to tunnel endpoints (#318)

rs: update dependencies for cg alerts

---

ts/src/contracts/index.ts
ts/src/management/idGeneration.ts

- Fixes import issue in TS SDK
-
-

Fix typescript import

---

cs/src/Connections/TunnelRelayTunnelHost.cs
cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs
ts/src/connections/tunnelRelayTunnelHost.ts
ts/test/tunnels-test/tunnelHostAndClientTests.ts

Fix a bug in the tunnel host `RefreshPorts` API, which could send port-forward requests before the SSH session was authenticated. That technically violates the SSH protocol even when the SSH authentication method is "none", though only the Go tunnel client was strict enough that it was a problem.

Fix RefreshPorts API for sessions not yet authenticated

---

ts/src/management/tunnelManagementHttpClient.ts

Fixes #
- Fix bug where last request was being sent with wrong params 
-
-

Fix error message issue in TS

---

cs/src/Management/TunnelManagementClient.cs

Fixes [#1343](https://github.com/orgs/microsoft/projects/115/views/18?filterQuery=&pane=issue&itemId=46695213)
- Displays the message received in the service response specific to the enforced policy.

Handle Forbidden response for Enterprise Policies

---

rs/src/contracts/tunnel_endpoint.rs
rs/src/management/http_client.rs

Fixes Rust endpoint request 
- Updates the endpoint update request to use the new format of tunnels/{tunnelid}/endpoints/{id}
-
-

Update rust endpoint requests

---

rs/src/management/http_client.rs

rs: add missing semicolon in partner UA header

---

.pipelines/typescript-build-and-publish.yaml

Updates the ESRP release task version to use cert based auth instead of secrets

Update esrp release task

---

.pipelines/typescript-build-and-publish.yaml

There was an issue with the ESRP configuration upon initial release yesterday. They have published a new version with slightly different parameters

Update ESRP release with new parameters

---

go/tunnels/ssh/client_session.go
go/tunnels/tunnels.go

- Updates listener to use IPv4 to better detect conflicts
-
-

Update TCP listener type

---

cs/src/Connections/ITunnelRelayStreamFactory.cs
cs/src/Connections/TunnelRelayConnection.cs
cs/src/Connections/TunnelRelayStreamFactory.cs
cs/src/Connections/WebSocketStream.cs
cs/test/TunnelsSDK.Test/Mocks/MockTunnelRelayStreamFactory.cs

Adding this to investigate codespaces connection issues
Set the environment variable DEVTUNNELS_LOG_WEBSOCKET_MESSAGES to true for the additional logging

Add logging for websocket stream read and write

---

.github/workflows/maven.yml
cs/src/Connections/WebSocketStream.cs

Change from `WebSocketStream.ReadAsync` to `WS.R` and `WebSocketStream.WriteAsync` to `WS.W` accordingly.

Reduce websocket logs to reduce log file size
